# Copyright (C) 2019-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/m30sdd/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/m30sdd

PRODUCT_COPY_FILES += \
    vendor/samsung/m30sdd/proprietary/etc/init/init.gpscommon.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.gpscommon.rc \
    vendor/samsung/m30sdd/proprietary/etc/somxreg.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/somxreg.conf \
    vendor/samsung/m30sdd/proprietary/lib/libcamerahardwareinterface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamerahardwareinterface.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomx263dsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomx263dsw.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomx264dsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomx264dsw.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxaacd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxaacd.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxadpcmd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxadpcmd.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxamrd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxamrd.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxcmn.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxcmn.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxcore.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxcore.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxflacd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxflacd.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxhevcdsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxhevcdsw.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxmp3d.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxmp3d.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxmp43d.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxmp43d.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxmp4vdsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxmp4vdsw.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxnaace.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxnaace.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxvc1dsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxvc1dsw.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxvp8d.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxvp8d.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxwmad.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxwmad.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxwmv7d.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxwmv7d.so \
    vendor/samsung/m30sdd/proprietary/lib/libsomxwmv8d.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomxwmv8d.so \
    vendor/samsung/m30sdd/proprietary/lib/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so \
    vendor/samsung/m30sdd/proprietary/lib/vendor.samsung_slsi.hardware.configstore-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.samsung_slsi.hardware.configstore-utils.so \
    vendor/samsung/m30sdd/proprietary/lib/vendor.samsung_slsi.hardware.configstore@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.samsung_slsi.hardware.configstore@1.0.so \
    vendor/samsung/m30sdd/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomx263dsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomx263dsw.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomx264dsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomx264dsw.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxaacd.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxaacd.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxadpcmd.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxadpcmd.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxamrd.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxamrd.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxcmn.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxcmn.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxcore.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxcore.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxflacd.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxflacd.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxhevcdsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxhevcdsw.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxmp3d.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxmp3d.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxmp43d.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxmp43d.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxmp4vdsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxmp4vdsw.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxnaace.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxnaace.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxvc1dsw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxvc1dsw.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxvp8d.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxvp8d.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxwmad.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxwmad.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxwmv7d.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxwmv7d.so \
    vendor/samsung/m30sdd/proprietary/lib64/libsomxwmv8d.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsomxwmv8d.so \
    vendor/samsung/m30sdd/proprietary/lib64/vendor.samsung.hardware.security.widevine.keyprovisioning@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.samsung.hardware.security.widevine.keyprovisioning@1.0.so \
    vendor/samsung/m30sdd/proprietary/lib64/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0.so \
    vendor/samsung/m30sdd/proprietary/lib64/vendor.samsung_slsi.hardware.configstore-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.samsung_slsi.hardware.configstore-utils.so \
    vendor/samsung/m30sdd/proprietary/lib64/vendor.samsung_slsi.hardware.configstore@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.samsung_slsi.hardware.configstore@1.0.so
PRODUCT_COPY_FILES += \
    vendor/samsung/m30sdd/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    
   


  
 
     


